// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHb5P7SCAmu6BA1eiDvG2sJlf2oY83Ls',
    appId: '1:586455766892:web:2da9f1378a4a60a3258549',
    messagingSenderId: '586455766892',
    projectId: 'moodbites-b07ed',
    authDomain: 'moodbites-b07ed.firebaseapp.com',
    storageBucket: 'moodbites-b07ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Ys3QFfHHXSJvUYsi9NgpfUb6yVxroBo',
    appId: '1:586455766892:android:dcceb6a7c7147a4a258549',
    messagingSenderId: '586455766892',
    projectId: 'moodbites-b07ed',
    storageBucket: 'moodbites-b07ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW9y_dc9xXcRCNRw95w9bcvKeUTCL9RKQ',
    appId: '1:586455766892:ios:764f9f5d78503c62258549',
    messagingSenderId: '586455766892',
    projectId: 'moodbites-b07ed',
    storageBucket: 'moodbites-b07ed.firebasestorage.app',
    iosBundleId: 'com.example.moodbites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfHb5P7SCAmu6BA1eiDvG2sJlf2oY83Ls',
    appId: '1:586455766892:web:d4ad28d619b703ff258549',
    messagingSenderId: '586455766892',
    projectId: 'moodbites-b07ed',
    authDomain: 'moodbites-b07ed.firebaseapp.com',
    storageBucket: 'moodbites-b07ed.firebasestorage.app',
  );
}
